if( WIN32 )
    set( A51_ENTROPY_INPUT_BACKEND
        "${CMAKE_CURRENT_LIST_DIR}/Input/backend/sdl/input_sdl.cpp"
    )
    set( A51_ENTROPY_NETWORK_BACKEND
        "${CMAKE_CURRENT_LIST_DIR}/Network/Backend/NetLib_Windows.cpp"
    )
    set( A51_ENTROPY_NETWORK_DEPENDENCIES ws2_32 )
elseif( CMAKE_SYSTEM_NAME MATCHES "^(Linux|Android)$" )
    set( A51_ENTROPY_INPUT_BACKEND
        "${CMAKE_CURRENT_LIST_DIR}/Input/backend/sdl/input_sdl.cpp"
    )
    set( A51_ENTROPY_NETWORK_BACKEND
        "${CMAKE_CURRENT_LIST_DIR}/Network/Backend/NetLib_POSIX.cpp"
    )
else()
    message( FATAL_ERROR "Entropy network backend is not defined for ${CMAKE_SYSTEM_NAME}." )
endif()

a51_add_project( Entropy STATIC
    SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}"
    SOURCES
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_channel_mgr.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_stream_decoder_factory.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_descriptor_runtime.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_element_channel_runtime.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_mgr.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_package.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_package_registry.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_runtime.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_runtime_commands.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_spatial_mgr.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_stream_controller.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_stream_mgr.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_stream_runtime.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_stream_voice_binder.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_voice_mgr.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/backend/audio_backend.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/backend/audio_output_mixer.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/backend/sdl/audio_output_sdl.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/codecs/mp3/audio_mp3_stream_decoder.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/codecs/mp3/audio_mp3_stream_decoder_state.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/SDLEngine/sdleng.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/SDLEngine/sdleng_composite.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/SDLEngine/sdleng_core.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/SDLEngine/sdleng_font.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/SDLEngine/sdleng_renderdraw.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/SDLEngine/sdleng_renderbuffer.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/SDLEngine/sdleng_rtarget.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/SDLEngine/sdleng_shader.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/SDLEngine/sdleng_state.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/SDLEngine/sdleng_utils.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/SDLEngine/sdleng_vram.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/SDLEngine/sdleng_window.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Input/e_Input.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Input/e_InputActions.cpp"
        ${A51_ENTROPY_INPUT_BACKEND}
        "${CMAKE_CURRENT_LIST_DIR}/Common/e_ScratchMem.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Common/e_SimpleAllocator.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Common/e_ECS.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Common/e_Text.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Common/e_View.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Common/e_Platform.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/IOManager/Device_Host/io_device_host.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/IOManager/Device_Host/io_device_host_stdio.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/IOManager/io_cache.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/IOManager/io_device.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/IOManager/io_dfs.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/IOManager/io_filesystem.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/IOManager/io_mgr.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/IOManager/io_request.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Network/FiFo.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Network/NetAddress.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Network/NetCommon.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Network/NetSocket.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/Network/NetStream.cpp"
        ${A51_ENTROPY_NETWORK_BACKEND}
        "${CMAKE_CURRENT_LIST_DIR}/Audio/codecs/mp3/audio_mp3_stream_decoder.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/codecs/mp3/audio_mp3_stream_decoder_state.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/e_RenderDraw.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/SDLEngine/sdleng_private.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/SDLEngine/sdleng_vulkan.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Entropy.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/e_Audio.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/e_Composite.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/e_Engine.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/e_Frame.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/e_Input.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Input/e_InputActions.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Input/e_Input_Gadget_Defines.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Input/backend/input_backend.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/SDLEngine/sdleng_window.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/e_Network.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/e_RenderTarget.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/e_RenderBuffer.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/e_RenderState.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/e_Shader.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/e_ECS.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/e_ScratchMem.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/e_SimpleAllocator.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/e_Text.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/e_View.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/e_VRAM.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_channel_mgr.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_command.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_command_queue.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_runtime.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_stream_decoder_factory.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_descriptor_runtime.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_element_channel_runtime.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/backend/audio_backend.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/backend/audio_render_command.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/backend/audio_render_command_queue.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_helpers.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_package.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_package_registry.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_types.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_package_format.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_spatial_mgr.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_spatial_types.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_stream_controller.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_stream_decoder.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_stream_mgr.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_stream_runtime.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_stream_voice_binder.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/audio_voice_mgr.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/backend/audio_output_mixer.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Audio/backend/sdl/audio_output_sdl.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/IOManager/Device_Host/io_device_host.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/IOManager/io_cache.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/IOManager/io_device.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/IOManager/io_dfs.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/IOManager/io_filesystem.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/IOManager/io_mgr.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/IOManager/io_request.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Network/FiFo.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Network/NetAddress.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Network/NetDefines.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Network/NetSocket.hpp"
        "${CMAKE_CURRENT_LIST_DIR}/Network/NetStream.hpp"
    DEPENDENCIES
        ${A51_ENTROPY_NETWORK_DEPENDENCIES}
    PRIVATE_INCLUDE_DIRECTORIES
        "${CMAKE_SOURCE_DIR}/Support"
        "${CMAKE_SOURCE_DIR}/xCore/x_files"
        "${CMAKE_SOURCE_DIR}/xCore/Entropy"
        "${CMAKE_SOURCE_DIR}/xCore/Entropy/Audio"
        "${CMAKE_SOURCE_DIR}/xCore/3rdParty"
        "${CMAKE_SOURCE_DIR}/xCore/3rdParty/SDL3/include"
)

if( TARGET a51::SDL3 )
    target_link_libraries( Entropy PUBLIC a51::SDL3 )
endif()
